# Generated by Django 3.1.7 on 2021-03-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_products', '0004_auto_20210303_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='media_root', verbose_name='عکس'),
        ),
    ]
