# Generated by Django 3.1.7 on 2021-03-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_products', '0008_auto_20210304_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
