# Generated by Django 3.1.7 on 2021-04-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_product_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
