# Generated by Django 3.1.7 on 2021-04-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug/ عنوان در url '),
        ),
    ]
