# Generated by Django 3.1.7 on 2021-03-26 07:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='قیمت')),
                ('image', models.ImageField(null=True, upload_to='django_product/', verbose_name='عکس')),
                ('active', models.BooleanField(verbose_name='فعال')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
