# Generated by Django 3.1.7 on 2021-03-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_products', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
