# Generated by Django 3.1.7 on 2021-04-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_products', '0003_auto_20210327_1248'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
