# Generated by Django 3.1.7 on 2021-04-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_product_category', '0002_auto_20210414_1648'),
        ('django_products', '0004_auto_20210413_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='project_product_category.Category'),
        ),
    ]
