# Generated by Django 3.1.7 on 2021-04-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_products', '0005_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
