# Generated by Django 3.1.7 on 2021-04-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_products', '0007_product_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_gallery',
            options={'verbose_name': 'گالری محصول', 'verbose_name_plural': 'گالری تصاوبر محصولات'},
        ),
    ]
